[package]
name = "rusty-dendrite"
version = "0.1.0"
authors = ["jeroen"]
edition = "2018"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "hello-world-server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "hello-world-client"
path = "src/client.rs"

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.2"